import os
import requests
import json
import random
from typing import Optional, List, Dict

# INTEGRATED GEMINI API KEYS:
INTEGRATED_GEMINI_KEYS = []

import re

def generate_mock_ai_response(prompt: str, system_instruction: Optional[str] = None) -> str:
    """
    Fail-Safe Response Generator: Dynamically parses incoming prompt variables 
    using regex and creates structured, context-rich markdown reports matching 
    the expected Gemini output schema.
    """
    prompt_lower = prompt.lower()
    
    # 1. ESG Audit
    if "esg" in prompt_lower or "environmental" in prompt_lower:
        total_vehicles = 10
        ev_vehicles = 4
        total_ships = 100
        perishables = 15
        
        m1 = re.search(r"Total Fleet Size:\s*(\d+)", prompt)
        if m1: total_vehicles = int(m1.group(1))
        m2 = re.search(r"EV & Clean Energy Fleet:\s*(\d+)", prompt)
        if m2: ev_vehicles = int(m2.group(1))
        m3 = re.search(r"Total Shipments Processed:\s*(\d+)", prompt)
        if m3: total_ships = int(m3.group(1))
        m4 = re.search(r"Cold Chain \(Perishable\) Cargo:\s*(\d+)", prompt)
        if m4: perishables = int(m4.group(1))
        
        ev_percent = (ev_vehicles / total_vehicles * 100) if total_vehicles else 0.0
        carbon_savings = ev_vehicles * 8.4
        non_ev = total_vehicles - ev_vehicles
        
        return f"""# 🌍 Logistix ESG Sustainability Audit Report

## 1. Environmental Impact Rating
* **Fleet Electrification:** **{ev_vehicles} / {total_vehicles} ({ev_percent:.1f}%)** vehicles are zero-emission (EVs/Drones).
* **Carbon Reduction Level:** **High**. The transition of {ev_vehicles} vehicles has reduced operations carbon footprint by an estimated **{carbon_savings:.1f} tons of CO₂ equivalent** annually.

## 2. Key Sustainability Risks
* **Fossil Fuel Reliance:** {non_ev} vehicles are still internal combustion engines, contributing to active urban emission zones.
* **Cold Chain Efficiency:** {perishables} perishable shipments require optimized refrigeration routing to prevent food waste and energy leakage.

## 3. Eco-Efficiency Suggestions
1. **Accelerate Fleet Transition:** Plan phase-out of remaining diesel vehicles by scaling EV deployment.
2. **Dynamic Route Optimization:** Utilize AI to minimize idle times at congestion points, saving up to 12% fuel.
3. **Solar-Powered Warehousing:** Transition base hubs to solar microgrids to offset charging grid load.

## 4. Alignment with UN SDGs
* **SDG 7 (Affordable and Clean Energy):** Promoted via EV charging.
* **SDG 11 (Sustainable Cities):** Reduced particulate emissions in urban centers.
* **SDG 13 (Climate Action):** Direct carbon avoidance from active EV/Drone operations.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 2. Safety Audit
    elif "safety audit" in prompt_lower:
        total_drivers = 5
        high_fatigue = 1
        zen_drivers = 2
        avg_safety = 88.5
        incidents = 0
        
        m1 = re.search(r"Total Drivers:\s*(\d+)", prompt)
        if m1: total_drivers = int(m1.group(1))
        m2 = re.search(r"Average Fleet Safety Score:\s*([\d.]+)%", prompt)
        if m2: avg_safety = float(m2.group(1))
        m3 = re.search(r"Drivers with Critical Fatigue\s*\(>65%\):\s*(\d+)", prompt)
        if m3: high_fatigue = int(m3.group(1))
        m4 = re.search(r"Active Zen Mode Sessions:\s*(\d+)", prompt)
        if m4: zen_drivers = int(m4.group(1))
        m5 = re.search(r"Safety Incidents logged today:\s*(\d+)", prompt)
        if m5: incidents = int(m5.group(1))
        
        safety_status = "Excellent" if avg_safety >= 85 else ("Moderate" if avg_safety >= 70 else "Poor")
        
        return f"""# 🛡️ Driver Safety & Risk Mitigation Audit

## 1. Driver Fatigue Analysis
* **High Fatigue Alert:** **{high_fatigue}** drivers are operating above the 65% fatigue index. Immediate rest shifts required.
* **Zen-mode Engagement:** **{zen_drivers}** out of {total_drivers} active drivers have active Zen-mode dashboard assistance.

## 2. Incident Risk Assessment
* **Average Fleet Safety Score:** **{avg_safety:.1f}% ({safety_status})** overall driving score.
* **Recent Safety Incidents:** **{incidents}** active safety incidents or vehicle breakdowns logged today.

## 3. Operational Safety Playbook Recommendations
1. **Mandatory Rest Enforcements:** Auto-flag drivers exceeding 65% fatigue and route them to nearest warehouse rest zone.
2. **Defensive Driving Training:** Focus on drivers with safety scores below 85% to mitigate braking incident risks.
3. **Haptic Band Alerts:** Sync wearable vitals bands to sound physical alarms during micro-sleep detection.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 3. Warehouse Hub Readiness / operational hub readiness
    elif "readiness & fleet strategy" in prompt_lower or "operational hub readiness" in prompt_lower:
        wh_name = "Unknown Hub"
        congestion_pct = 0.0
        inbound_count = 0
        capacity = 5
        drone_count = 0
        total_drivers = 0
        high_fatigue = 0
        total_vehicles = 0
        avg_vehicle_health = 100.0
        unhealthy_vehicles = 0
        
        m_depot = re.search(r"depot '([^']+)'", prompt)
        if m_depot:
            wh_name = m_depot.group(1)
            
        m_congestion = re.search(r"Inbound Congestion:\s*([\d.]+)%\s*\((\d+)\s*shipments inbound,\s*base capacity\s*(\d+)\)", prompt)
        if m_congestion:
            congestion_pct = float(m_congestion.group(1))
            inbound_count = int(m_congestion.group(2))
            capacity = int(m_congestion.group(3))
            
        m_drones = re.search(r"Total Drone Fleet:\s*(\d+)", prompt)
        if m_drones:
            drone_count = int(m_drones.group(1))
            
        m_drivers = re.search(r"Total Registered Drivers:\s*(\d+)", prompt)
        if m_drivers:
            total_drivers = int(m_drivers.group(1))
            
        m_fatigue = re.search(r"High-Fatigue Drivers\s*\(>60%\):\s*(\d+)", prompt)
        if m_fatigue:
            high_fatigue = int(m_fatigue.group(1))
            
        m_vehicles = re.search(r"Total Vehicles:\s*(\d+)", prompt)
        if m_vehicles:
            total_vehicles = int(m_vehicles.group(1))
            
        m_health = re.search(r"Average Vehicle Health:\s*([\d.]+)", prompt)
        if m_health:
            avg_vehicle_health = float(m_health.group(1))
            
        m_servicing = re.search(r"Servicing Required\s*\(<80% health\):\s*(\d+)", prompt)
        if m_servicing:
            unhealthy_vehicles = int(m_servicing.group(1))
            
        fitness_score = max(0, min(100, int(100 - (congestion_pct * 0.4) - (high_fatigue * 10) - (unhealthy_vehicles * 15))))
        
        return f"""# 🏢 Warehouse Hub Readiness Report ({wh_name})

## 1. Depot Fitness Score: {fitness_score}/100
* **Status:** {"Excellent 🟢" if fitness_score >= 80 else ("Caution 🟡" if fitness_score >= 50 else "Critical Risk 🔴")}
* **Inbound Congestion:** {congestion_pct:.1f}% ({inbound_count} shipments active, capacity {capacity}).

## 2. Operational Bottlenecks
* **Fatigue Impact:** {high_fatigue} out of {total_drivers} registered drivers exceed safe fatigue limits (>60%).
* **Maintenance Backlog:** {unhealthy_vehicles} out of {total_vehicles} active vehicles require servicing (average fleet health: {avg_vehicle_health:.1f}%).

## 3. Drone Fleet Readiness
* **Active Drone Pads:** {drone_count} operational pads ready for short-range autonomous deliveries.
* **Dispatch Strategy:** Recommended to shift 15% of low-weight deliveries to drones to alleviate ground traffic.

## 4. Safety & Fleet Strategy Recommendations
1. **Fatigue Mitigation:** Enforce immediate rest protocols for the {high_fatigue} flagged driver(s).
2. **Maintenance Scheduling:** Order immediate preventive maintenance checks for the {unhealthy_vehicles} degraded vehicle(s).

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 4. Demand Forecast
    elif "demand forecast" in prompt_lower:
        wh_name = "Unknown Hub"
        total_inbound = 0
        total_weight = 0.0
        avg_weight = 0.0
        cold_chain_count = 0
        high_value_inbound = 0
        
        m_depot = re.search(r"hub '([^']+)'", prompt)
        if m_depot:
            wh_name = m_depot.group(1)
            
        m1 = re.search(r"Active Inbound Shipments:\s*(\d+)", prompt)
        if m1: total_inbound = int(m1.group(1))
        
        m2 = re.search(r"Total Inbound Payload Weight:\s*([\d.]+) kg", prompt)
        if m2: total_weight = float(m2.group(1))
        
        m_avg = re.search(r"average\s*([\d.]+)\s*kg/shipment", prompt)
        if m_avg: avg_weight = float(m_avg.group(1))
        
        m3 = re.search(r"Cold-Chain \(Temperature-Controlled\) Shipments:\s*(\d+)", prompt)
        if m3: cold_chain_count = int(m3.group(1))
        
        m4 = re.search(r"High-Value Shipments\s*\(>₹1,00,000\):\s*(\d+)", prompt)
        if m4: high_value_inbound = int(m4.group(1))
        
        return f"""# 📊 Hub Demand & Volume Forecast ({wh_name})

## 1. Current vs. Predicted Volume
* **Active Inbound Shipments:** **{total_inbound}** shipments scheduled to arrive in the next 12 hours.
* **Total Payload Weight:** **{total_weight:.1f} kg** (averaging {avg_weight:.1f} kg per shipment).

## 2. Cargo Specialization Indicators
* **Cold-Chain Shipments:** **{cold_chain_count}** require climate-controlled slots.
* **High-Value Assets:** **{high_value_inbound}** shipments exceed ₹1,00,000 in cargo value, requiring active high-security transit logs.

## 3. Predicted Inbound Congestion
* **Peak Loading Times:** Expected peak surge between 2 PM and 5 PM.
* **Storage Allocation:** Recommendation to clear staging zones to accommodate inbound volume.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 5. Fatigue Report
    elif "fatigue & safety risk report" in prompt_lower:
        wh_name = "Unknown Hub"
        total_drivers = 0
        high_risk = 0
        med_risk = 0
        unfit = 0
        
        m_depot = re.search(r"hub '([^']+)'", prompt)
        if m_depot:
            wh_name = m_depot.group(1)
            
        m1 = re.search(r"Total Drivers Monitored:\s*(\d+)", prompt)
        if m1: total_drivers = int(m1.group(1))
        
        m2 = re.search(r"High Fatigue Risk\s*\(>60% Score\):\s*(\d+)", prompt)
        if m2: high_risk = int(m2.group(1))
        
        m3 = re.search(r"Medium Fatigue Risk\s*\(30-60% Score\):\s*(\d+)", prompt)
        if m3: med_risk = int(m3.group(1))
        
        m4 = re.search(r"Declared Temporarily Unfit\s*\(Mandatory Rest\):\s*(\d+)", prompt)
        if m4: unfit = int(m4.group(1))
        
        # Extract driver sample details from the prompt to make it super realistic
        driver_details = []
        lines = prompt.split('\n')
        for line in lines:
            if line.startswith("- ") and "Fatigue Score" in line:
                driver_details.append(line)
                
        details_md = "\n".join(driver_details) if driver_details else "*No driver telemetry records available.*"
        
        return f"""# 💤 Driver Fatigue & Safety Risk Report ({wh_name})

## 1. Hub Risk Rating
* **Monitored Drivers:** {total_drivers} on-duty personnel.
* **High Risk (>60% fatigue):** **{high_risk}** drivers flagged.
* **Medium Risk (30-60% fatigue):** **{med_risk}** drivers.
* **Mandatory Off-Duty Enforcements:** **{unfit}** drivers placed offline.

## 2. Critical Fatigue Alerts (Live Sample)
{details_md}

## 3. Mitigation & Rest Scheduling Recommendations
1. **Immediate Break Allocations:** Enforce mandatory rest intervals for the {high_risk} driver(s) showing critical fatigue metrics.
2. **Shift Rotations:** Align off-duty rotations to prevent additional fatigue build-up.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 6. Daily Briefing
    elif "daily briefing" in prompt_lower:
        wh_name = "Unknown Hub"
        inbound_backlog = 0
        outbound_backlog = 0
        weather_summary = "Weather data unavailable"
        active_drivers = 0
        total_drivers = 0
        healthy_vehicles = 0
        total_vehicles = 0
        
        m_depot = re.search(r"hub '([^']+)'", prompt)
        if m_depot:
            wh_name = m_depot.group(1)
            
        m1 = re.search(r"Inbound Backlog Shipments:\s*(\d+)", prompt)
        if m1: inbound_backlog = int(m1.group(1))
        
        m2 = re.search(r"Outbound Backlog Shipments:\s*(\d+)", prompt)
        if m2: outbound_backlog = int(m2.group(1))
        
        m_wx = re.search(r"Live Hub Weather\s*\(Open-Meteo\):\s*(.+)", prompt)
        if m_wx: weather_summary = m_wx.group(1).strip()
        
        m_fleet = re.search(r"Fleet Readiness:\s*(\d+)/(\d+)", prompt)
        if m_fleet:
            active_drivers = int(m_fleet.group(1))
            total_drivers = int(m_fleet.group(2))
            
        m_veh = re.search(r"Operational Vehicles:\s*(\d+)/(\d+)", prompt)
        if m_veh:
            healthy_vehicles = int(m_veh.group(1))
            total_vehicles = int(m_veh.group(2))
            
        return f"""# 📋 Morning Operational AI Daily Briefing ({wh_name})

## 1. Operational Weather Alert
* **Conditions:** {weather_summary}

## 2. Backlog & Congestion Status
* **Inbound Backlog:** **{inbound_backlog}** shipments pending.
* **Outbound Backlog:** **{outbound_backlog}** shipments queued.

## 3. Fleet Readiness Indicator
* **Active Drivers:** {active_drivers} of {total_drivers} drivers on-duty.
* **Operational Vehicles:** {healthy_vehicles} of {total_vehicles} vehicles fit for service (>=80% health score).

## 4. Top Priority Action Items for Today
1. **Weather Precautions:** Adjust transit speed limits to account for precipitation or local delays.
2. **Backlog Clearing:** Prioritize routing of the {inbound_backlog} pending inbound shipments.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 7. Fleet Audit
    elif "diagnostic fleet audit" in prompt_lower:
        high_fatigue = 0
        low_health_vehicles = 0
        
        m1 = re.search(r"Drivers with critical fatigue\s*\(>60\):\s*(\d+)", prompt)
        if m1: high_fatigue = int(m1.group(1))
        
        m2 = re.search(r"Vehicles needing immediate service\s*\(<80% health\):\s*(\d+)", prompt)
        if m2: low_health_vehicles = int(m2.group(1))
        
        # Extract drivers and vehicles lists
        drivers_list = []
        vehicles_list = []
        
        lines = prompt.split('\n')
        parsing_drivers = False
        parsing_vehicles = False
        for line in lines:
            if "### Personnel" in line:
                parsing_drivers = True
                parsing_vehicles = False
                continue
            if "### Assets" in line:
                parsing_drivers = False
                parsing_vehicles = True
                continue
            if line.startswith("Drivers with") or line.startswith("Vehicles needing"):
                parsing_drivers = False
                parsing_vehicles = False
                continue
            
            if parsing_drivers and line.strip().startswith("- "):
                drivers_list.append(line.strip())
            if parsing_vehicles and line.strip().startswith("- "):
                vehicles_list.append(line.strip())
                
        drivers_md = "\n".join(drivers_list) if drivers_list else "*No critical driver personnel warnings.*"
        vehicles_md = "\n".join(vehicles_list) if vehicles_list else "*No vehicles needing servicing.*"
        
        return f"""# 📊 Diagnostic Fleet Audit Report

## 1. Personnel Fatigue Warnings
* **Critical Fatigue (>60%):** {high_fatigue} drivers are flagged.
* **Registered Telemetry Details:**
{drivers_md}

## 2. Asset Maintenance Advice
* **Degraded Assets (<80% health):** {low_health_vehicles} vehicles need immediate inspection.
* **Vehicle Fleet Log:**
{vehicles_md}

## 3. Direct Fleet Optimization Recommendations
1. **Targeted Driver Scheduling:** Rotate the {high_fatigue} high-fatigue drivers offline to prevent safety hazards.
2. **Preventive Maintenance:** Dispatch the {low_health_vehicles} degraded vehicle(s) for immediate servicing to keep operations at 100% capacity.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # 8. Customer Support Chatbot / Assistant
    elif "customer support" in prompt_lower or "order id" in prompt_lower or "live details" in prompt_lower:
        order_id = "N/A"
        item = "Package"
        status = "In Transit"
        transit = "on schedule"
        vehicle = "Vehicle"
        
        m_id = re.search(r"Order ID:\s*(.+)", prompt)
        if m_id: order_id = m_id.group(1).strip()
        m_item = re.search(r"Item:\s*(.+)", prompt)
        if m_item: item = m_item.group(1).strip()
        m_status = re.search(r"Current Status:\s*(.+)", prompt)
        if m_status: status = m_status.group(1).strip()
        m_transit = re.search(r"Transit Progress:\s*(.+)", prompt)
        if m_transit: transit = m_transit.group(1).strip()
        m_vehicle = re.search(r"Assigned Vehicle:\s*(.+)", prompt)
        if m_vehicle: vehicle = m_vehicle.group(1).strip()
        
        return f"Hello! Your shipment {order_id} ({item}) is currently {status}. {transit}. It is assigned to {vehicle}. Let me know if you have any questions or need further details!"

    # 9. Strategy Optimizer
    elif "strategy" in prompt_lower or "revenue" in prompt_lower:
        revenue = 100000
        expenses = 40000
        
        m1 = re.search(r"Total Revenue generated:\s*₹?(\d+)", prompt)
        if m1: revenue = int(m1.group(1))
        m2 = re.search(r"Total Operating Expenses:\s*₹?(\d+)", prompt)
        if m2: expenses = int(m2.group(1))
        
        margin = ((revenue - expenses) / revenue * 100) if revenue else 0
        
        return f"""# 📈 Operational Strategy Optimization Report

## 1. Financial Performance Analysis
* **Operating Revenue:** ₹{revenue:,}
* **Operating Expenses:** ₹{expenses:,}
* **Net Profit Margin:** **{margin:.1f}%**

## 2. Recommended Action Items
1. **Reduce Fuel Overheads:** Consolidate routes to reduce mileage.
2. **Asset Management:** Transition older fleet vehicles to EV to save maintenance costs.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router using original database telemetry.*"""

    # Default fallback
    return f"""### 🔮 Logistix Operations Advisor (Fail-Safe Briefing)

* **Operations Analysis:** The system is functioning normally under local AI optimization rules.
* **Advisory Details:** Live parameters parsed successfully. Vitals: normal, vehicle telemetry: stable, environmental factor: optimized.
* **Mitigation Recommendation:** Proceed with current route configuration and schedule standard driver health assessments.

*Note: Live Google Gemini API is currently unavailable. This report was generated by the local AI fail-safe router.*"""


def call_gemini(prompt: str, system_instruction: Optional[str] = None, api_key: Optional[str] = None) -> str:
    """
    Calls the Gemini 2.0 Flash API directly using the requests library.
    Automatically rotates through all keys in the pool on rate limit or error.
    If all keys fail (e.g., rate limits, invalid keys, or billing constraints), 
    transparently falls back to local high-fidelity simulated reports.
    """
    all_keys = []
    
    # Parse passed keys (comma-separated rotation pool)
    if api_key:
        all_keys.extend([k.strip() for k in api_key.split(",") if k.strip()])
            
    # Filter out empty placeholder/template strings
    keys_list = [k for k in all_keys if k and not k.startswith("YOUR_") and len(k) > 10]
    
    if not keys_list:
        print("[Gemini Fail-Safe] No keys configured. Activating Fail-Safe Auto-Fallback.")
        return generate_mock_ai_response(prompt, system_instruction)
    
    # Shuffle so we spread load evenly across keys
    shuffled_keys = keys_list.copy()
    random.shuffle(shuffled_keys)
    
    headers = {"Content-Type": "application/json"}
    
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }]
    }
    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }
    
    last_error = None
    
    # Try every key in the pool before giving up
    for key in shuffled_keys:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={key}"
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            
            if response.status_code == 200:
                res_data = response.json()
                candidates = res_data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "")
                raise ValueError(f"Failed to parse Gemini API response candidates: {response.text}")
            
            # Extract detailed error message from response JSON if possible
            try:
                err_json = response.json()
                err_msg = err_json.get("error", {}).get("message", response.text)
            except:
                err_msg = response.text
                
            if response.status_code == 429:
                # Rate limited — try next key
                last_error = f"Key ending ...{key[-6:]} hit rate limit (429): {err_msg}"
                continue
            
            elif response.status_code in (401, 403):
                # Invalid key — try next key
                last_error = f"Key ending ...{key[-6:]} is invalid or unauthorized ({response.status_code}): {err_msg}"
                continue
            
            else:
                last_error = f"Gemini API returned error {response.status_code}: {err_msg}"
                continue
                
        except Exception as e:
            last_error = f"Connection error with key ...{key[-6:]}: {str(e)}"
            continue
    
    # All keys exhausted
    print(f"[Gemini Fail-Safe Warning] All keys failed. Last error: {last_error or 'Unknown error'}. Activating Fail-Safe Auto-Fallback.")
    return generate_mock_ai_response(prompt, system_instruction)
