import os
import requests
import json
import random
from typing import Optional, List, Dict

# INTEGRATED GEMINI API KEYS:
INTEGRATED_GEMINI_KEYS = []

import re

def generate_mock_ai_response(prompt: str, system_instruction: Optional[str] = None) -> str:
    """
    Fail-Safe Response Generator: Dynamically parses incoming prompt variables 
    using regex and creates structured, context-rich markdown reports matching 
    the expected Gemini output schema.
    """
    prompt_lower = prompt.lower()
    
    # 1. ESG Audit
    if "esg" in prompt_lower or "environmental" in prompt_lower:
        total_vehicles = 10
        ev_vehicles = 4
        total_ships = 100
        perishables = 15
        
        m1 = re.search(r"Total Fleet Size:\s*(\d+)", prompt)
        if m1: total_vehicles = int(m1.group(1))
        m2 = re.search(r"EV & Clean Energy Fleet:\s*(\d+)", prompt)
        if m2: ev_vehicles = int(m2.group(1))
        m3 = re.search(r"Total Shipments Processed:\s*(\d+)", prompt)
        if m3: total_ships = int(m3.group(1))
        m4 = re.search(r"Cold Chain \(Perishable\) Cargo:\s*(\d+)", prompt)
        if m4: perishables = int(m4.group(1))
        
        ev_percent = (ev_vehicles / total_vehicles * 100) if total_vehicles else 0.0
        carbon_savings = ev_vehicles * 8.4
        non_ev = total_vehicles - ev_vehicles
        
        return f"""# 🌍 Logistix ESG Sustainability Audit Report

## 1. Environmental Impact Rating
* **Fleet Electrification:** **{ev_vehicles} / {total_vehicles} ({ev_percent:.1f}%)** vehicles are zero-emission (EVs/Drones).
* **Carbon Reduction Level:** **High**. The transition of {ev_vehicles} vehicles has reduced operations carbon footprint by an estimated **{carbon_savings:.1f} tons of CO₂ equivalent** annually.

## 2. Key Sustainability Risks
* **Fossil Fuel Reliance:** {non_ev} vehicles are still internal combustion engines, contributing to active urban emission zones.
* **Cold Chain Efficiency:** {perishables} perishable shipments require optimized refrigeration routing to prevent food waste and energy leakage.

## 3. Eco-Efficiency Suggestions
1. **Accelerate Fleet Transition:** Plan phase-out of remaining diesel vehicles by scaling EV deployment.
2. **Dynamic Route Optimization:** Utilize AI to minimize idle times at congestion points, saving up to 12% fuel.
3. **Solar-Powered Warehousing:** Transition base hubs to solar microgrids to offset charging grid load.

## 4. Alignment with UN SDGs
* **SDG 7 (Affordable and Clean Energy):** Promoted via EV charging.
* **SDG 11 (Sustainable Cities):** Reduced particulate emissions in urban centers.
* **SDG 13 (Climate Action):** Direct carbon avoidance from active EV/Drone operations.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router.*"""

    # 2. Safety Audit
    elif "safety" in prompt_lower or "fatigue" in prompt_lower:
        total_drivers = 5
        high_fatigue = 1
        zen_drivers = 2
        avg_safety = 88.5
        incidents = 0
        
        m1 = re.search(r"Total Personnel:\s*(\d+)", prompt)
        if m1: total_drivers = int(m1.group(1))
        m2 = re.search(r"Drivers with critical fatigue:\s*(\d+)", prompt)
        if m2: high_fatigue = int(m2.group(1))
        m3 = re.search(r"Zen-mode active drivers:\s*(\d+)", prompt)
        if m3: zen_drivers = int(m3.group(1))
        m4 = re.search(r"Average Driver Safety score:\s*([\d.]+)", prompt)
        if m4: avg_safety = float(m4.group(1))
        m5 = re.search(r"Recent Transit Incidents:\s*(\d+)", prompt)
        if m5: incidents = int(m5.group(1))
        
        if "critical fatigue" in prompt_lower and not m1:
            m_fatigue = re.search(r"Drivers with critical fatigue\s*\(>60\):\s*(\d+)", prompt)
            if m_fatigue: high_fatigue = int(m_fatigue.group(1))
            
        return f"""# 🛡️ Driver Safety & Risk Mitigation Audit

## 1. Driver Fatigue Analysis
* **High Fatigue Alert:** **{high_fatigue}** drivers are operating above the 65% fatigue index. Immediate rest shifts required.
* **Zen-mode Engagement:** **{zen_drivers}** drivers have active Zen-mode dashboard assistance, helping maintain lower stress metrics.

## 2. Incident Risk Assessment
* **Average Safety Score:** **{avg_safety:.1f}%** overall driving score. Main risk areas identified: harsh braking and night driving.
* **Recent Safety Incidents:** **{incidents}** active safety alerts triggered in the current operations window.

## 3. Operational Safety Playbook Recommendations
1. **Mandatory Rest Enforcements:** Auto-flag drivers exceeding 65% fatigue and route them to nearest warehouse rest zone.
2. **Defensive Driving Training:** Focus on drivers with safety scores below 85% to mitigate braking incident risks.
3. **Haptic Band Alerts:** Sync wearable vitals bands to sound physical alarms during micro-sleep detection.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router.*"""

    # 3. Warehouse Hub Readiness
    elif "readiness" in prompt_lower or "warehouse" in prompt_lower:
        wh_name = "Mumbai Hub"
        pending = 0
        active_v = 0
        fatigue_d = 0
        load = 0.0
        
        m_name = re.search(r"Warehouse Name:\s*(.+)", prompt)
        if m_name: wh_name = m_name.group(1).strip()
        m1 = re.search(r"Pending Shipments:\s*(\d+)", prompt)
        if m1: pending = int(m1.group(1))
        m2 = re.search(r"Active Vehicles:\s*(\d+)", prompt)
        if m2: active_v = int(m2.group(1))
        m3 = re.search(r"Drivers needing rest:\s*(\d+)", prompt)
        if m3: fatigue_d = int(m3.group(1))
        m4 = re.search(r"Capacity load:\s*([\d.]+)", prompt)
        if m4: load = float(m4.group(1))
        
        return f"""# 🏢 Warehouse Hub Readiness Report ({wh_name})

## 1. Capacity & Traffic Load
* **Hub Utilization:** Current capacity load is at **{load:.1f}%**. Space utilization is optimal.
* **Pending Shipments:** **{pending}** shipments are currently queued for processing.

## 2. Fleet & Personnel Allocation
* **Active Vehicles:** **{active_v}** delivery vehicles are ready for dispatch or active.
* **Driver Wellness Check:** **{fatigue_d}** drivers are flagged as needing immediate sleep/rest rotations.

## 3. Hub Action Plan
1. **Load Balancing:** Shift secondary dispatch routes to lower-congestion sister hubs.
2. **Shift Management:** Deploy standby drivers to relieve personnel currently exceeding maximum drive hours.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router.*"""

    # 4. Demand Forecast
    elif "demand" in prompt_lower or "forecast" in prompt_lower:
        load = 50.0
        inbound = 5
        
        m1 = re.search(r"Current Load:\s*([\d.]+)", prompt)
        if m1: load = float(m1.group(1))
        m2 = re.search(r"Inbound shipments:\s*(\d+)", prompt)
        if m2: inbound = int(m2.group(1))
        
        return f"""# 📊 Hub Demand & Volume Forecast

## 1. Current vs. Predicted Volume
* **Current Operations Load:** **{load:.1f}%** capacity occupied.
* **Incoming Traffic:** **{inbound}** inbound shipments scheduled to arrive in the next 12 hours.

## 2. Predicted Inbound Congestion
* **Peak Loading Times:** Expected peak surge between 2 PM and 5 PM.
* **Storage Allocation:** Recommendation to clear staging zone B to accommodate inbound volume.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router.*"""

    # 5. Customer Chatbot / Assistant
    elif "customer support" in prompt_lower or "order id" in prompt_lower or "live details" in prompt_lower:
        order_id = "N/A"
        item = "Package"
        status = "In Transit"
        transit = "on schedule"
        vehicle = "Vehicle"
        
        m_id = re.search(r"Order ID:\s*(.+)", prompt)
        if m_id: order_id = m_id.group(1).strip()
        m_item = re.search(r"Item:\s*(.+)", prompt)
        if m_item: item = m_item.group(1).strip()
        m_status = re.search(r"Current Status:\s*(.+)", prompt)
        if m_status: status = m_status.group(1).strip()
        m_transit = re.search(r"Transit Progress:\s*(.+)", prompt)
        if m_transit: transit = m_transit.group(1).strip()
        m_vehicle = re.search(r"Assigned Vehicle:\s*(.+)", prompt)
        if m_vehicle: vehicle = m_vehicle.group(1).strip()
        
        return f"Hello! Your shipment {order_id} ({item}) is currently {status}. {transit}. It is assigned to {vehicle}. Let me know if you have any questions or need further details!"

    # 6. Strategy Optimizer
    elif "strategy" in prompt_lower or "revenue" in prompt_lower:
        revenue = 100000
        expenses = 40000
        
        m1 = re.search(r"Total Revenue generated:\s*₹?(\d+)", prompt)
        if m1: revenue = int(m1.group(1))
        m2 = re.search(r"Total Operating Expenses:\s*₹?(\d+)", prompt)
        if m2: expenses = int(m2.group(1))
        
        margin = ((revenue - expenses) / revenue * 100) if revenue else 0
        
        return f"""# 📈 Operational Strategy Optimization Report

## 1. Financial Performance Analysis
* **Operating Revenue:** ₹{revenue:,}
* **Operating Expenses:** ₹{expenses:,}
* **Net Profit Margin:** **{margin:.1f}%**

## 2. Recommended Action Items
1. **Reduce Fuel Overheads:** Consolidate routes to reduce mileage.
2. **Asset Management:** Transition older fleet vehicles to EV to save maintenance costs.

*Note: Live Google Gemini API is currently unavailable (Quota Exhausted/Disabled). This report was generated by the local AI fail-safe router.*"""

    # Default fallback
    return f"""### 🔮 Logistix Operations Advisor (Fail-Safe Briefing)

* **Operations Analysis:** The system is functioning normally under local AI optimization rules.
* **Advisory Details:** Live parameters parsed successfully. Vitals: normal, vehicle telemetry: stable, environmental factor: optimized.
* **Mitigation Recommendation:** Proceed with current route configuration and schedule standard driver health assessments.

*Note: Live Google Gemini API is currently unavailable. This report was generated by the local AI fail-safe router.*"""


def call_gemini(prompt: str, system_instruction: Optional[str] = None, api_key: Optional[str] = None) -> str:
    """
    Calls the Gemini 2.0 Flash API directly using the requests library.
    Automatically rotates through all keys in the pool on rate limit or error.
    If all keys fail (e.g., rate limits, invalid keys, or billing constraints), 
    transparently falls back to local high-fidelity simulated reports.
    """
    all_keys = []
    
    # Parse passed keys (comma-separated rotation pool)
    if api_key:
        all_keys.extend([k.strip() for k in api_key.split(",") if k.strip()])
            
    # Filter out empty placeholder/template strings
    keys_list = [k for k in all_keys if k and not k.startswith("YOUR_") and len(k) > 10]
    
    if not keys_list:
        print("[Gemini Fail-Safe] No keys configured. Activating Fail-Safe Auto-Fallback.")
        return generate_mock_ai_response(prompt, system_instruction)
    
    # Shuffle so we spread load evenly across keys
    shuffled_keys = keys_list.copy()
    random.shuffle(shuffled_keys)
    
    headers = {"Content-Type": "application/json"}
    
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }]
    }
    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }
    
    last_error = None
    
    # Try every key in the pool before giving up
    for key in shuffled_keys:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={key}"
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            
            if response.status_code == 200:
                res_data = response.json()
                candidates = res_data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "")
                raise ValueError(f"Failed to parse Gemini API response candidates: {response.text}")
            
            # Extract detailed error message from response JSON if possible
            try:
                err_json = response.json()
                err_msg = err_json.get("error", {}).get("message", response.text)
            except:
                err_msg = response.text
                
            if response.status_code == 429:
                # Rate limited — try next key
                last_error = f"Key ending ...{key[-6:]} hit rate limit (429): {err_msg}"
                continue
            
            elif response.status_code in (401, 403):
                # Invalid key — try next key
                last_error = f"Key ending ...{key[-6:]} is invalid or unauthorized ({response.status_code}): {err_msg}"
                continue
            
            else:
                last_error = f"Gemini API returned error {response.status_code}: {err_msg}"
                continue
                
        except Exception as e:
            last_error = f"Connection error with key ...{key[-6:]}: {str(e)}"
            continue
    
    # All keys exhausted
    print(f"[Gemini Fail-Safe Warning] All keys failed. Last error: {last_error or 'Unknown error'}. Activating Fail-Safe Auto-Fallback.")
    return generate_mock_ai_response(prompt, system_instruction)
